// Code generated by software.amazon.smithy.rust.codegen.smithy-rs. DO NOT EDIT.
/// All possible error types for this service.
#[non_exhaustive]
#[derive(std::fmt::Debug)]
pub enum Error {
	#[allow(missing_docs)] // documentation missing in model
	BadRequestError(crate::error::BadRequestError),
	#[allow(missing_docs)] // documentation missing in model
	ForbiddenError(crate::error::ForbiddenError),
	#[allow(missing_docs)] // documentation missing in model
	InternalError(crate::error::InternalError),
	#[allow(missing_docs)] // documentation missing in model
	NotFoundError(crate::error::NotFoundError),
	#[allow(missing_docs)] // documentation missing in model
	RateLimitError(crate::error::RateLimitError),
	#[allow(missing_docs)] // documentation missing in model
	UnauthorizedError(crate::error::UnauthorizedError),
	/// An unhandled error occurred.
	Unhandled(Box<dyn std::error::Error + Send + Sync + 'static>),
}
impl std::fmt::Display for Error {
	fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
		match self {
			Error::BadRequestError(inner) => inner.fmt(f),
			Error::ForbiddenError(inner) => inner.fmt(f),
			Error::InternalError(inner) => inner.fmt(f),
			Error::NotFoundError(inner) => inner.fmt(f),
			Error::RateLimitError(inner) => inner.fmt(f),
			Error::UnauthorizedError(inner) => inner.fmt(f),
			Error::Unhandled(inner) => inner.fmt(f),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::CompleteUploadError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(err: aws_smithy_http::result::SdkError<crate::error::CompleteUploadError, R>) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::CompleteUploadErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::CompleteUploadErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::CompleteUploadErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::CompleteUploadErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::CompleteUploadErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::CompleteUploadErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::CompleteUploadErrorKind::Unhandled(inner) => Error::Unhandled(inner),
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::ConvertTeamError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(err: aws_smithy_http::result::SdkError<crate::error::ConvertTeamError, R>) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::ConvertTeamErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::ConvertTeamErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::ConvertTeamErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::ConvertTeamErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::ConvertTeamErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::ConvertTeamErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::ConvertTeamErrorKind::Unhandled(inner) => Error::Unhandled(inner),
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::CreateCloudTokenError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::CreateCloudTokenError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::CreateCloudTokenErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::CreateCloudTokenErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::CreateCloudTokenErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::CreateCloudTokenErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::CreateCloudTokenErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::CreateCloudTokenErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::CreateCloudTokenErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::CreateGameError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(err: aws_smithy_http::result::SdkError<crate::error::CreateGameError, R>) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::CreateGameErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::CreateGameErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::CreateGameErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::CreateGameErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::CreateGameErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::CreateGameErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::CreateGameErrorKind::Unhandled(inner) => Error::Unhandled(inner),
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::CreateGameBuildError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(err: aws_smithy_http::result::SdkError<crate::error::CreateGameBuildError, R>) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::CreateGameBuildErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::CreateGameBuildErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::CreateGameBuildErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::CreateGameBuildErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::CreateGameBuildErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::CreateGameBuildErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::CreateGameBuildErrorKind::Unhandled(inner) => Error::Unhandled(inner),
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::CreateGameCdnSiteError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::CreateGameCdnSiteError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::CreateGameCdnSiteErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::CreateGameCdnSiteErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::CreateGameCdnSiteErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::CreateGameCdnSiteErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::CreateGameCdnSiteErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::CreateGameCdnSiteErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::CreateGameCdnSiteErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::CreateGameNamespaceError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::CreateGameNamespaceError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::CreateGameNamespaceErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::CreateGameNamespaceErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::CreateGameNamespaceErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::CreateGameNamespaceErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::CreateGameNamespaceErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::CreateGameNamespaceErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::CreateGameNamespaceErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R>
	From<
		aws_smithy_http::result::SdkError<
			crate::error::CreateGameNamespaceTokenDevelopmentError,
			R,
		>,
	> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<
			crate::error::CreateGameNamespaceTokenDevelopmentError,
			R,
		>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::CreateGameNamespaceTokenDevelopmentErrorKind::InternalError(
					inner,
				) => Error::InternalError(inner),
				crate::error::CreateGameNamespaceTokenDevelopmentErrorKind::RateLimitError(
					inner,
				) => Error::RateLimitError(inner),
				crate::error::CreateGameNamespaceTokenDevelopmentErrorKind::ForbiddenError(
					inner,
				) => Error::ForbiddenError(inner),
				crate::error::CreateGameNamespaceTokenDevelopmentErrorKind::UnauthorizedError(
					inner,
				) => Error::UnauthorizedError(inner),
				crate::error::CreateGameNamespaceTokenDevelopmentErrorKind::NotFoundError(
					inner,
				) => Error::NotFoundError(inner),
				crate::error::CreateGameNamespaceTokenDevelopmentErrorKind::BadRequestError(
					inner,
				) => Error::BadRequestError(inner),
				crate::error::CreateGameNamespaceTokenDevelopmentErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R>
	From<aws_smithy_http::result::SdkError<crate::error::CreateGameNamespaceTokenPublicError, R>>
	for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<
			crate::error::CreateGameNamespaceTokenPublicError,
			R,
		>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::CreateGameNamespaceTokenPublicErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::CreateGameNamespaceTokenPublicErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::CreateGameNamespaceTokenPublicErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::CreateGameNamespaceTokenPublicErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::CreateGameNamespaceTokenPublicErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::CreateGameNamespaceTokenPublicErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::CreateGameNamespaceTokenPublicErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::CreateGameVersionError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::CreateGameVersionError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::CreateGameVersionErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::CreateGameVersionErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::CreateGameVersionErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::CreateGameVersionErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::CreateGameVersionErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::CreateGameVersionErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::CreateGameVersionErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::DeleteMatchmakerLobbyError, R>>
	for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::DeleteMatchmakerLobbyError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::DeleteMatchmakerLobbyErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::DeleteMatchmakerLobbyErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::DeleteMatchmakerLobbyErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::DeleteMatchmakerLobbyErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::DeleteMatchmakerLobbyErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::DeleteMatchmakerLobbyErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::DeleteMatchmakerLobbyErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::ExportMatchmakerLobbyHistoryError, R>>
	for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::ExportMatchmakerLobbyHistoryError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::ExportMatchmakerLobbyHistoryErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::ExportMatchmakerLobbyHistoryErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::ExportMatchmakerLobbyHistoryErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::ExportMatchmakerLobbyHistoryErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::ExportMatchmakerLobbyHistoryErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::ExportMatchmakerLobbyHistoryErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::ExportMatchmakerLobbyHistoryErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::GetGameByIdError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(err: aws_smithy_http::result::SdkError<crate::error::GetGameByIdError, R>) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::GetGameByIdErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::GetGameByIdErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::GetGameByIdErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::GetGameByIdErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::GetGameByIdErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::GetGameByIdErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::GetGameByIdErrorKind::Unhandled(inner) => Error::Unhandled(inner),
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::GetGameNamespaceByIdError, R>>
	for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::GetGameNamespaceByIdError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::GetGameNamespaceByIdErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::GetGameNamespaceByIdErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::GetGameNamespaceByIdErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::GetGameNamespaceByIdErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::GetGameNamespaceByIdErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::GetGameNamespaceByIdErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::GetGameNamespaceByIdErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::GetGamesError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(err: aws_smithy_http::result::SdkError<crate::error::GetGamesError, R>) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::GetGamesErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::GetGamesErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::GetGamesErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::GetGamesErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::GetGamesErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::GetGamesErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::GetGamesErrorKind::Unhandled(inner) => Error::Unhandled(inner),
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::GetGameVersionByIdError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::GetGameVersionByIdError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::GetGameVersionByIdErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::GetGameVersionByIdErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::GetGameVersionByIdErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::GetGameVersionByIdErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::GetGameVersionByIdErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::GetGameVersionByIdErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::GetGameVersionByIdErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R>
	From<
		aws_smithy_http::result::SdkError<
			crate::error::GetNamespaceAnalyticsMatchmakerLiveError,
			R,
		>,
	> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<
			crate::error::GetNamespaceAnalyticsMatchmakerLiveError,
			R,
		>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::GetNamespaceAnalyticsMatchmakerLiveErrorKind::InternalError(
					inner,
				) => Error::InternalError(inner),
				crate::error::GetNamespaceAnalyticsMatchmakerLiveErrorKind::RateLimitError(
					inner,
				) => Error::RateLimitError(inner),
				crate::error::GetNamespaceAnalyticsMatchmakerLiveErrorKind::ForbiddenError(
					inner,
				) => Error::ForbiddenError(inner),
				crate::error::GetNamespaceAnalyticsMatchmakerLiveErrorKind::UnauthorizedError(
					inner,
				) => Error::UnauthorizedError(inner),
				crate::error::GetNamespaceAnalyticsMatchmakerLiveErrorKind::NotFoundError(
					inner,
				) => Error::NotFoundError(inner),
				crate::error::GetNamespaceAnalyticsMatchmakerLiveErrorKind::BadRequestError(
					inner,
				) => Error::BadRequestError(inner),
				crate::error::GetNamespaceAnalyticsMatchmakerLiveErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::GetNamespaceLobbyError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::GetNamespaceLobbyError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::GetNamespaceLobbyErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::GetNamespaceLobbyErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::GetNamespaceLobbyErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::GetNamespaceLobbyErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::GetNamespaceLobbyErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::GetNamespaceLobbyErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::GetNamespaceLobbyErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::GetRayPerfLogsError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(err: aws_smithy_http::result::SdkError<crate::error::GetRayPerfLogsError, R>) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::GetRayPerfLogsErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::GetRayPerfLogsErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::GetRayPerfLogsErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::GetRayPerfLogsErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::GetRayPerfLogsErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::GetRayPerfLogsErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::GetRayPerfLogsErrorKind::Unhandled(inner) => Error::Unhandled(inner),
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::GetRegionTiersError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(err: aws_smithy_http::result::SdkError<crate::error::GetRegionTiersError, R>) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::GetRegionTiersErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::GetRegionTiersErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::GetRegionTiersErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::GetRegionTiersErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::GetRegionTiersErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::GetRegionTiersErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::GetRegionTiersErrorKind::Unhandled(inner) => Error::Unhandled(inner),
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::GetTeamBillingError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(err: aws_smithy_http::result::SdkError<crate::error::GetTeamBillingError, R>) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::GetTeamBillingErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::GetTeamBillingErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::GetTeamBillingErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::GetTeamBillingErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::GetTeamBillingErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::GetTeamBillingErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::GetTeamBillingErrorKind::Unhandled(inner) => Error::Unhandled(inner),
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::GetTeamPaymentsListError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::GetTeamPaymentsListError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::GetTeamPaymentsListErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::GetTeamPaymentsListErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::GetTeamPaymentsListErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::GetTeamPaymentsListErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::GetTeamPaymentsListErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::GetTeamPaymentsListErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::GetTeamPaymentsListErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::GetTeamTransfersListError, R>>
	for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::GetTeamTransfersListError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::GetTeamTransfersListErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::GetTeamTransfersListErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::GetTeamTransfersListErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::GetTeamTransfersListErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::GetTeamTransfersListErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::GetTeamTransfersListErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::GetTeamTransfersListErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::InspectError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(err: aws_smithy_http::result::SdkError<crate::error::InspectError, R>) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::InspectErrorKind::InternalError(inner) => Error::InternalError(inner),
				crate::error::InspectErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::InspectErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::InspectErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::InspectErrorKind::NotFoundError(inner) => Error::NotFoundError(inner),
				crate::error::InspectErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::InspectErrorKind::Unhandled(inner) => Error::Unhandled(inner),
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::ListGameBuildsError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(err: aws_smithy_http::result::SdkError<crate::error::ListGameBuildsError, R>) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::ListGameBuildsErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::ListGameBuildsErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::ListGameBuildsErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::ListGameBuildsErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::ListGameBuildsErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::ListGameBuildsErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::ListGameBuildsErrorKind::Unhandled(inner) => Error::Unhandled(inner),
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::ListGameCdnSitesError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::ListGameCdnSitesError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::ListGameCdnSitesErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::ListGameCdnSitesErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::ListGameCdnSitesErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::ListGameCdnSitesErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::ListGameCdnSitesErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::ListGameCdnSitesErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::ListGameCdnSitesErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::ListNamespaceLobbiesError, R>>
	for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::ListNamespaceLobbiesError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::ListNamespaceLobbiesErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::ListNamespaceLobbiesErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::ListNamespaceLobbiesErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::ListNamespaceLobbiesErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::ListNamespaceLobbiesErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::ListNamespaceLobbiesErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::ListNamespaceLobbiesErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::RemoveNamespaceDomainError, R>>
	for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::RemoveNamespaceDomainError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::RemoveNamespaceDomainErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::RemoveNamespaceDomainErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::RemoveNamespaceDomainErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::RemoveNamespaceDomainErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::RemoveNamespaceDomainErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::RemoveNamespaceDomainErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::RemoveNamespaceDomainErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::TeamBillingCheckoutError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::TeamBillingCheckoutError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::TeamBillingCheckoutErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::TeamBillingCheckoutErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::TeamBillingCheckoutErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::TeamBillingCheckoutErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::TeamBillingCheckoutErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::TeamBillingCheckoutErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::TeamBillingCheckoutErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R>
	From<aws_smithy_http::result::SdkError<crate::error::ToggleNamespaceDomainPublicAuthError, R>>
	for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<
			crate::error::ToggleNamespaceDomainPublicAuthError,
			R,
		>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::ToggleNamespaceDomainPublicAuthErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::ToggleNamespaceDomainPublicAuthErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::ToggleNamespaceDomainPublicAuthErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::ToggleNamespaceDomainPublicAuthErrorKind::UnauthorizedError(
					inner,
				) => Error::UnauthorizedError(inner),
				crate::error::ToggleNamespaceDomainPublicAuthErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::ToggleNamespaceDomainPublicAuthErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::ToggleNamespaceDomainPublicAuthErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R>
	From<
		aws_smithy_http::result::SdkError<
			crate::error::UpdateGameNamespaceMatchmakerConfigError,
			R,
		>,
	> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<
			crate::error::UpdateGameNamespaceMatchmakerConfigError,
			R,
		>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::UpdateGameNamespaceMatchmakerConfigErrorKind::InternalError(
					inner,
				) => Error::InternalError(inner),
				crate::error::UpdateGameNamespaceMatchmakerConfigErrorKind::RateLimitError(
					inner,
				) => Error::RateLimitError(inner),
				crate::error::UpdateGameNamespaceMatchmakerConfigErrorKind::ForbiddenError(
					inner,
				) => Error::ForbiddenError(inner),
				crate::error::UpdateGameNamespaceMatchmakerConfigErrorKind::UnauthorizedError(
					inner,
				) => Error::UnauthorizedError(inner),
				crate::error::UpdateGameNamespaceMatchmakerConfigErrorKind::NotFoundError(
					inner,
				) => Error::NotFoundError(inner),
				crate::error::UpdateGameNamespaceMatchmakerConfigErrorKind::BadRequestError(
					inner,
				) => Error::BadRequestError(inner),
				crate::error::UpdateGameNamespaceMatchmakerConfigErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::UpdateGameNamespaceVersionError, R>>
	for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::UpdateGameNamespaceVersionError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::UpdateGameNamespaceVersionErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::UpdateGameNamespaceVersionErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::UpdateGameNamespaceVersionErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::UpdateGameNamespaceVersionErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::UpdateGameNamespaceVersionErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::UpdateGameNamespaceVersionErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::UpdateGameNamespaceVersionErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::UpdateNamespaceDomainError, R>>
	for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::UpdateNamespaceDomainError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::UpdateNamespaceDomainErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::UpdateNamespaceDomainErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::UpdateNamespaceDomainErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::UpdateNamespaceDomainErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::UpdateNamespaceDomainErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::UpdateNamespaceDomainErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::UpdateNamespaceDomainErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::ValidateGameError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(err: aws_smithy_http::result::SdkError<crate::error::ValidateGameError, R>) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::ValidateGameErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::ValidateGameErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::ValidateGameErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::ValidateGameErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::ValidateGameErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::ValidateGameErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::ValidateGameErrorKind::Unhandled(inner) => Error::Unhandled(inner),
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::ValidateGameNamespaceError, R>>
	for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::ValidateGameNamespaceError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::ValidateGameNamespaceErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::ValidateGameNamespaceErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::ValidateGameNamespaceErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::ValidateGameNamespaceErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::ValidateGameNamespaceErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::ValidateGameNamespaceErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::ValidateGameNamespaceErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R>
	From<
		aws_smithy_http::result::SdkError<
			crate::error::ValidateGameNamespaceMatchmakerConfigError,
			R,
		>,
	> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<
			crate::error::ValidateGameNamespaceMatchmakerConfigError,
			R,
		>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::ValidateGameNamespaceMatchmakerConfigErrorKind::InternalError(
					inner,
				) => Error::InternalError(inner),
				crate::error::ValidateGameNamespaceMatchmakerConfigErrorKind::RateLimitError(
					inner,
				) => Error::RateLimitError(inner),
				crate::error::ValidateGameNamespaceMatchmakerConfigErrorKind::ForbiddenError(
					inner,
				) => Error::ForbiddenError(inner),
				crate::error::ValidateGameNamespaceMatchmakerConfigErrorKind::UnauthorizedError(
					inner,
				) => Error::UnauthorizedError(inner),
				crate::error::ValidateGameNamespaceMatchmakerConfigErrorKind::NotFoundError(
					inner,
				) => Error::NotFoundError(inner),
				crate::error::ValidateGameNamespaceMatchmakerConfigErrorKind::BadRequestError(
					inner,
				) => Error::BadRequestError(inner),
				crate::error::ValidateGameNamespaceMatchmakerConfigErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R>
	From<
		aws_smithy_http::result::SdkError<
			crate::error::ValidateGameNamespaceTokenDevelopmentError,
			R,
		>,
	> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<
			crate::error::ValidateGameNamespaceTokenDevelopmentError,
			R,
		>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::ValidateGameNamespaceTokenDevelopmentErrorKind::InternalError(
					inner,
				) => Error::InternalError(inner),
				crate::error::ValidateGameNamespaceTokenDevelopmentErrorKind::RateLimitError(
					inner,
				) => Error::RateLimitError(inner),
				crate::error::ValidateGameNamespaceTokenDevelopmentErrorKind::ForbiddenError(
					inner,
				) => Error::ForbiddenError(inner),
				crate::error::ValidateGameNamespaceTokenDevelopmentErrorKind::UnauthorizedError(
					inner,
				) => Error::UnauthorizedError(inner),
				crate::error::ValidateGameNamespaceTokenDevelopmentErrorKind::NotFoundError(
					inner,
				) => Error::NotFoundError(inner),
				crate::error::ValidateGameNamespaceTokenDevelopmentErrorKind::BadRequestError(
					inner,
				) => Error::BadRequestError(inner),
				crate::error::ValidateGameNamespaceTokenDevelopmentErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::ValidateGameVersionError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(
		err: aws_smithy_http::result::SdkError<crate::error::ValidateGameVersionError, R>,
	) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::ValidateGameVersionErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::ValidateGameVersionErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::ValidateGameVersionErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::ValidateGameVersionErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::ValidateGameVersionErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::ValidateGameVersionErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::ValidateGameVersionErrorKind::Unhandled(inner) => {
					Error::Unhandled(inner)
				}
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl<R> From<aws_smithy_http::result::SdkError<crate::error::ValidateTeamError, R>> for Error
where
	R: Send + Sync + std::fmt::Debug + 'static,
{
	fn from(err: aws_smithy_http::result::SdkError<crate::error::ValidateTeamError, R>) -> Self {
		match err {
			aws_smithy_http::result::SdkError::ServiceError { err, .. } => match err.kind {
				crate::error::ValidateTeamErrorKind::InternalError(inner) => {
					Error::InternalError(inner)
				}
				crate::error::ValidateTeamErrorKind::RateLimitError(inner) => {
					Error::RateLimitError(inner)
				}
				crate::error::ValidateTeamErrorKind::ForbiddenError(inner) => {
					Error::ForbiddenError(inner)
				}
				crate::error::ValidateTeamErrorKind::UnauthorizedError(inner) => {
					Error::UnauthorizedError(inner)
				}
				crate::error::ValidateTeamErrorKind::NotFoundError(inner) => {
					Error::NotFoundError(inner)
				}
				crate::error::ValidateTeamErrorKind::BadRequestError(inner) => {
					Error::BadRequestError(inner)
				}
				crate::error::ValidateTeamErrorKind::Unhandled(inner) => Error::Unhandled(inner),
			},
			_ => Error::Unhandled(err.into()),
		}
	}
}
impl std::error::Error for Error {}
