[package]
name = "rivet-toolchain"
version = "0.1.0"
edition = "2021"
build = "build.rs"
license = "Apache-2.0"
rust-version = "1.75"
description = "Build & scale realtime applications"
homepage = "https://rivet.gg"
repository = "https://github.com/rivet-gg/cli"

[dependencies]
async-stream = "0.3.3"
console = "0.15"
dirs = "5.0"
futures-util = "0.3"
humansize = "1.1"
ignore = "0.4"
indicatif = "0.17"
lz4 = "1.24"
mime_guess = "2.0"
regex = "1.10"
reqwest = { version = "0.11", default-features = false, features = ["stream", "blocking", "rustls-tls"] }
rivet-api = { package = "rivet-api-ee", path = "../../sdks/rust" }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["raw_value"] }
strum = { version = "0.24", features = ["derive"] }
tar = "0.4.40"
tempfile = "3.13.0"
tokio = { version = "1.40.0", default-features = false, features = ["fs", "macros", "process", "rt", "io-util"] }
tokio-util = { version = "0.7", default-features = false, features = ["io-util"] }
typed-path = "0.7.0"
url = "2.5.0"
uuid = { version = "1.3", features = ["v4"] }
which = "5.0.0"
zip = "0.5"
const_format = "0.2.32"
pkg-version = "1.0.0"
anyhow = "1.0"
rivet-deno-embed = { path = "../deno-embed" }
rivet-js-utils-embed = { path = "../js-utils-embed" }
lazy_static = "1.5.0"
sha1 = "0.10.6"
jsonc-parser = { version = "0.26.2", features = ["serde"] }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.27", default-features = false, features = ["user", "signal"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.48", features = ["Win32_Foundation", "Win32_System_Diagnostics", "Win32_System_Diagnostics_ToolHelp", "Win32_System_Threading", "Win32_System_Console", "Win32_System_ProcessStatus"] }

[dev-dependencies]
assert_cmd = "2.0"

[build-dependencies]
anyhow = "1.0"
vergen-git2 = "1.0.0"

