/*
 * Rivet API EE
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EeBillingRegionUsage {
    #[serde(rename = "region_id")]
    pub region_id: uuid::Uuid,
    /// Total CPU usage time in milliseconds.
    #[serde(rename = "uptime")]
    pub uptime: i64,
}

impl EeBillingRegionUsage {
    pub fn new(region_id: uuid::Uuid, uptime: i64) -> EeBillingRegionUsage {
        EeBillingRegionUsage {
            region_id,
            uptime,
        }
    }
}


