/*
 * Rivet API EE
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EeBackendDeployRequest {
    #[serde(rename = "upload_id")]
    pub upload_id: uuid::Uuid,
    #[serde(rename = "variables", skip_serializing_if = "Option::is_none")]
    pub variables: Option<::std::collections::HashMap<String, crate::models::EeBackendUpdateVariable>>,
}

impl EeBackendDeployRequest {
    pub fn new(upload_id: uuid::Uuid) -> EeBackendDeployRequest {
        EeBackendDeployRequest {
            upload_id,
            variables: None,
        }
    }
}


