/*
 * Rivet API EE
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EeCloudBackendProjectsCreateResponse {
    #[serde(rename = "project")]
    pub project: Box<crate::models::EeBackendProject>,
    #[serde(rename = "project_id")]
    pub project_id: uuid::Uuid,
}

impl EeCloudBackendProjectsCreateResponse {
    pub fn new(project: crate::models::EeBackendProject, project_id: uuid::Uuid) -> EeCloudBackendProjectsCreateResponse {
        EeCloudBackendProjectsCreateResponse {
            project: Box::new(project),
            project_id,
        }
    }
}


