/*
 * Rivet API EE
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EeCloudGamesBillingPlanConfig {
    #[serde(rename = "dynamic_servers_capacity")]
    pub dynamic_servers_capacity: Vec<crate::models::EeCloudGamesBillingDynamicServersCapacityRegionConfig>,
}

impl EeCloudGamesBillingPlanConfig {
    pub fn new(dynamic_servers_capacity: Vec<crate::models::EeCloudGamesBillingDynamicServersCapacityRegionConfig>) -> EeCloudGamesBillingPlanConfig {
        EeCloudGamesBillingPlanConfig {
            dynamic_servers_capacity,
        }
    }
}


