/*
 * Rivet API EE
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EeCloudBackendProjectsEnvsGetConfigResponse {
	#[serde(rename = "config")]
	pub config: Box<crate::models::EeBackendNeonProjectConfig>,
	#[serde(rename = "watch")]
	pub watch: Box<crate::models::WatchResponse>,
}

impl EeCloudBackendProjectsEnvsGetConfigResponse {
	pub fn new(
		config: crate::models::EeBackendNeonProjectConfig,
		watch: crate::models::WatchResponse,
	) -> EeCloudBackendProjectsEnvsGetConfigResponse {
		EeCloudBackendProjectsEnvsGetConfigResponse {
			config: Box::new(config),
			watch: Box::new(watch),
		}
	}
}
