/*
 * Rivet API EE
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EeCloudGroupsBillingStripePortalSessionIntent {
    #[serde(rename = "general")]
    General,
    #[serde(rename = "payment_method_update")]
    PaymentMethodUpdate,

}

impl ToString for EeCloudGroupsBillingStripePortalSessionIntent {
    fn to_string(&self) -> String {
        match self {
            Self::General => String::from("general"),
            Self::PaymentMethodUpdate => String::from("payment_method_update"),
        }
    }
}

impl Default for EeCloudGroupsBillingStripePortalSessionIntent {
    fn default() -> EeCloudGroupsBillingStripePortalSessionIntent {
        Self::General
    }
}




