/*
 * Rivet API EE
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EeCloudBackendProjectsListResponse {
	#[serde(rename = "projects")]
	pub projects: Vec<crate::models::EeBackendProject>,
	#[serde(rename = "watch")]
	pub watch: Box<crate::models::WatchResponse>,
}

impl EeCloudBackendProjectsListResponse {
	pub fn new(
		projects: Vec<crate::models::EeBackendProject>,
		watch: crate::models::WatchResponse,
	) -> EeCloudBackendProjectsListResponse {
		EeCloudBackendProjectsListResponse {
			projects,
			watch: Box::new(watch),
		}
	}
}
