/*
 * Rivet API EE
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EeCloudOpengbProjectsEnvsUpdateVariablesRequest {
    #[serde(rename = "variables")]
    pub variables: ::std::collections::HashMap<String, crate::models::EeOpengbVariable>,
}

impl EeCloudOpengbProjectsEnvsUpdateVariablesRequest {
    pub fn new(variables: ::std::collections::HashMap<String, crate::models::EeOpengbVariable>) -> EeCloudOpengbProjectsEnvsUpdateVariablesRequest {
        EeCloudOpengbProjectsEnvsUpdateVariablesRequest {
            variables,
        }
    }
}


