/*
 * Rivet API EE
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EeCloudPlayerCountByGameModeDataSet {
    #[serde(rename = "game_mode_id")]
    pub game_mode_id: Vec<uuid::Uuid>,
    #[serde(rename = "game_mode_name_id")]
    pub game_mode_name_id: Vec<String>,
    #[serde(rename = "player_count")]
    pub player_count: Vec<i64>,
    #[serde(rename = "ts")]
    pub ts: Vec<i64>,
}

impl EeCloudPlayerCountByGameModeDataSet {
    pub fn new(game_mode_id: Vec<uuid::Uuid>, game_mode_name_id: Vec<String>, player_count: Vec<i64>, ts: Vec<i64>) -> EeCloudPlayerCountByGameModeDataSet {
        EeCloudPlayerCountByGameModeDataSet {
            game_mode_id,
            game_mode_name_id,
            player_count,
            ts,
        }
    }
}


