/*
 * Rivet API EE
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EeCloudBackendProjectsGetResponse {
	#[serde(rename = "project")]
	pub project: Box<crate::models::EeBackendProject>,
	#[serde(rename = "watch")]
	pub watch: Box<crate::models::WatchResponse>,
}

impl EeCloudBackendProjectsGetResponse {
	pub fn new(
		project: crate::models::EeBackendProject,
		watch: crate::models::WatchResponse,
	) -> EeCloudBackendProjectsGetResponse {
		EeCloudBackendProjectsGetResponse {
			project: Box::new(project),
			watch: Box::new(watch),
		}
	}
}
