/*
 * Rivet API EE
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EeCloudLobbyCountDataSet {
	#[serde(rename = "lobby_closed_count")]
	pub lobby_closed_count: Vec<i64>,
	#[serde(rename = "lobby_count")]
	pub lobby_count: Vec<i64>,
	#[serde(rename = "lobby_preemptive_count")]
	pub lobby_preemptive_count: Vec<i64>,
	#[serde(rename = "lobby_unready_count")]
	pub lobby_unready_count: Vec<i64>,
	#[serde(rename = "ts")]
	pub ts: Vec<i64>,
}

impl EeCloudLobbyCountDataSet {
	pub fn new(
		lobby_closed_count: Vec<i64>,
		lobby_count: Vec<i64>,
		lobby_preemptive_count: Vec<i64>,
		lobby_unready_count: Vec<i64>,
		ts: Vec<i64>,
	) -> EeCloudLobbyCountDataSet {
		EeCloudLobbyCountDataSet {
			lobby_closed_count,
			lobby_count,
			lobby_preemptive_count,
			lobby_unready_count,
			ts,
		}
	}
}
