/*
 * Rivet API EE
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EeCloudGamesBillingDynamicServersCapacityRegion {
	#[serde(rename = "cores")]
	pub cores: i32,
	#[serde(rename = "region")]
	pub region: Box<crate::models::CloudRegionSummary>,
}

impl EeCloudGamesBillingDynamicServersCapacityRegion {
	pub fn new(
		cores: i32,
		region: crate::models::CloudRegionSummary,
	) -> EeCloudGamesBillingDynamicServersCapacityRegion {
		EeCloudGamesBillingDynamicServersCapacityRegion {
			cores,
			region: Box::new(region),
		}
	}
}
