/*
 * Rivet API EE
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EeCloudOpengbProjectsEnvsDeployRequest {
	#[serde(rename = "modules")]
	pub modules: ::std::collections::HashMap<String, crate::models::EeOpengbModule>,
	#[serde(rename = "upload_id")]
	pub upload_id: uuid::Uuid,
}

impl EeCloudOpengbProjectsEnvsDeployRequest {
	pub fn new(
		modules: ::std::collections::HashMap<String, crate::models::EeOpengbModule>,
		upload_id: uuid::Uuid,
	) -> EeCloudOpengbProjectsEnvsDeployRequest {
		EeCloudOpengbProjectsEnvsDeployRequest { modules, upload_id }
	}
}
