/*
 * Rivet API EE
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EeCloudAnalyticsVariantQuery {
    #[serde(rename = "matchmaker_overview")]
    MatchmakerOverview,
    #[serde(rename = "player_count")]
    PlayerCount,
    #[serde(rename = "player_count_by_region")]
    PlayerCountByRegion,
    #[serde(rename = "player_count_by_game_mode")]
    PlayerCountByGameMode,
    #[serde(rename = "lobby_count")]
    LobbyCount,
    #[serde(rename = "lobby_count_by_region")]
    LobbyCountByRegion,
    #[serde(rename = "lobby_count_by_game_mode")]
    LobbyCountByGameMode,
    #[serde(rename = "avg_play_duration")]
    AvgPlayDuration,
    #[serde(rename = "avg_play_duration_by_region")]
    AvgPlayDurationByRegion,
    #[serde(rename = "avg_play_duration_by_game_mode")]
    AvgPlayDurationByGameMode,
    #[serde(rename = "new_players_per_second")]
    NewPlayersPerSecond,
    #[serde(rename = "new_lobbies_per_second")]
    NewLobbiesPerSecond,
    #[serde(rename = "destroyed_lobbies_by_failure")]
    DestroyedLobbiesByFailure,
    #[serde(rename = "destroyed_lobbies_by_exit_code")]
    DestroyedLobbiesByExitCode,
    #[serde(rename = "failed_lobbies")]
    FailedLobbies,
    #[serde(rename = "lobby_ready_time")]
    LobbyReadyTime,

}

impl ToString for EeCloudAnalyticsVariantQuery {
    fn to_string(&self) -> String {
        match self {
            Self::MatchmakerOverview => String::from("matchmaker_overview"),
            Self::PlayerCount => String::from("player_count"),
            Self::PlayerCountByRegion => String::from("player_count_by_region"),
            Self::PlayerCountByGameMode => String::from("player_count_by_game_mode"),
            Self::LobbyCount => String::from("lobby_count"),
            Self::LobbyCountByRegion => String::from("lobby_count_by_region"),
            Self::LobbyCountByGameMode => String::from("lobby_count_by_game_mode"),
            Self::AvgPlayDuration => String::from("avg_play_duration"),
            Self::AvgPlayDurationByRegion => String::from("avg_play_duration_by_region"),
            Self::AvgPlayDurationByGameMode => String::from("avg_play_duration_by_game_mode"),
            Self::NewPlayersPerSecond => String::from("new_players_per_second"),
            Self::NewLobbiesPerSecond => String::from("new_lobbies_per_second"),
            Self::DestroyedLobbiesByFailure => String::from("destroyed_lobbies_by_failure"),
            Self::DestroyedLobbiesByExitCode => String::from("destroyed_lobbies_by_exit_code"),
            Self::FailedLobbies => String::from("failed_lobbies"),
            Self::LobbyReadyTime => String::from("lobby_ready_time"),
        }
    }
}

impl Default for EeCloudAnalyticsVariantQuery {
    fn default() -> EeCloudAnalyticsVariantQuery {
        Self::MatchmakerOverview
    }
}




