// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-09-12T00:20:08.669Z

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface FooCallSelfRequest
 */
export interface FooCallSelfRequest {}

/**
 * Check if a given object implements the FooCallSelfRequest interface.
 */
export function instanceOfFooCallSelfRequest(
  _value: object,
): _value is FooCallSelfRequest {
  return true;
}

export function FooCallSelfRequestFromJSON(json: any): FooCallSelfRequest {
  return FooCallSelfRequestFromJSONTyped(json, false);
}

export function FooCallSelfRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): FooCallSelfRequest {
  if (json == null) {
    return json;
  }
  return {};
}

export function FooCallSelfRequestToJSON(
  value?: FooCallSelfRequest | null,
): any {
  if (value == null) {
    return value;
  }
  return {};
}
