/* tslint:disable */
/* eslint-disable */
/**
 * Rivet SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FriendsSendRequestResponseFriendRequest } from './FriendsSendRequestResponseFriendRequest';
import {
    FriendsSendRequestResponseFriendRequestFromJSON,
    FriendsSendRequestResponseFriendRequestFromJSONTyped,
    FriendsSendRequestResponseFriendRequestToJSON,
} from './FriendsSendRequestResponseFriendRequest';

/**
 * 
 * @export
 * @interface FriendsListOutgoingFriendRequestsResponse
 */
export interface FriendsListOutgoingFriendRequestsResponse {
    /**
     * 
     * @type {Array<FriendsSendRequestResponseFriendRequest>}
     * @memberof FriendsListOutgoingFriendRequestsResponse
     */
    friendRequests: Array<FriendsSendRequestResponseFriendRequest>;
}

/**
 * Check if a given object implements the FriendsListOutgoingFriendRequestsResponse interface.
 */
export function instanceOfFriendsListOutgoingFriendRequestsResponse(value: object): value is FriendsListOutgoingFriendRequestsResponse {
    if (!('friendRequests' in value) || value['friendRequests'] === undefined) return false;
    return true;
}

export function FriendsListOutgoingFriendRequestsResponseFromJSON(json: any): FriendsListOutgoingFriendRequestsResponse {
    return FriendsListOutgoingFriendRequestsResponseFromJSONTyped(json, false);
}

export function FriendsListOutgoingFriendRequestsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FriendsListOutgoingFriendRequestsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'friendRequests': ((json['friendRequests'] as Array<any>).map(FriendsSendRequestResponseFriendRequestFromJSON)),
    };
}

export function FriendsListOutgoingFriendRequestsResponseToJSON(value?: FriendsListOutgoingFriendRequestsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'friendRequests': ((value['friendRequests'] as Array<any>).map(FriendsSendRequestResponseFriendRequestToJSON)),
    };
}

