/* tslint:disable */
/* eslint-disable */
/**
 * Rivet SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FriendsSendRequestResponseFriendRequest } from './FriendsSendRequestResponseFriendRequest';
import {
    FriendsSendRequestResponseFriendRequestFromJSON,
    FriendsSendRequestResponseFriendRequestFromJSONTyped,
    FriendsSendRequestResponseFriendRequestToJSON,
} from './FriendsSendRequestResponseFriendRequest';

/**
 * 
 * @export
 * @interface FriendsSendRequestResponse
 */
export interface FriendsSendRequestResponse {
    /**
     * 
     * @type {FriendsSendRequestResponseFriendRequest}
     * @memberof FriendsSendRequestResponse
     */
    friendRequest: FriendsSendRequestResponseFriendRequest;
}

/**
 * Check if a given object implements the FriendsSendRequestResponse interface.
 */
export function instanceOfFriendsSendRequestResponse(value: object): value is FriendsSendRequestResponse {
    if (!('friendRequest' in value) || value['friendRequest'] === undefined) return false;
    return true;
}

export function FriendsSendRequestResponseFromJSON(json: any): FriendsSendRequestResponse {
    return FriendsSendRequestResponseFromJSONTyped(json, false);
}

export function FriendsSendRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FriendsSendRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'friendRequest': FriendsSendRequestResponseFriendRequestFromJSON(json['friendRequest']),
    };
}

export function FriendsSendRequestResponseToJSON(value?: FriendsSendRequestResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'friendRequest': FriendsSendRequestResponseFriendRequestToJSON(value['friendRequest']),
    };
}

