/* tslint:disable */
/* eslint-disable */
/**
 * Rivet SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FriendsListFriendsResponseFriendsInner } from './FriendsListFriendsResponseFriendsInner';
import {
    FriendsListFriendsResponseFriendsInnerFromJSON,
    FriendsListFriendsResponseFriendsInnerFromJSONTyped,
    FriendsListFriendsResponseFriendsInnerToJSON,
} from './FriendsListFriendsResponseFriendsInner';

/**
 * 
 * @export
 * @interface FriendsListFriendsResponse
 */
export interface FriendsListFriendsResponse {
    /**
     * 
     * @type {Array<FriendsListFriendsResponseFriendsInner>}
     * @memberof FriendsListFriendsResponse
     */
    friends: Array<FriendsListFriendsResponseFriendsInner>;
}

/**
 * Check if a given object implements the FriendsListFriendsResponse interface.
 */
export function instanceOfFriendsListFriendsResponse(value: object): value is FriendsListFriendsResponse {
    if (!('friends' in value) || value['friends'] === undefined) return false;
    return true;
}

export function FriendsListFriendsResponseFromJSON(json: any): FriendsListFriendsResponse {
    return FriendsListFriendsResponseFromJSONTyped(json, false);
}

export function FriendsListFriendsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FriendsListFriendsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'friends': ((json['friends'] as Array<any>).map(FriendsListFriendsResponseFriendsInnerFromJSON)),
    };
}

export function FriendsListFriendsResponseToJSON(value?: FriendsListFriendsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'friends': ((value['friends'] as Array<any>).map(FriendsListFriendsResponseFriendsInnerToJSON)),
    };
}

