/* tslint:disable */
/* eslint-disable */
/**
 * Rivet SDK
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FriendsListIncomingFriendRequestsRequest
 */
export interface FriendsListIncomingFriendRequestsRequest {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof FriendsListIncomingFriendRequestsRequest
     */
    userToken: string;
}

/**
 * Check if a given object implements the FriendsListIncomingFriendRequestsRequest interface.
 */
export function instanceOfFriendsListIncomingFriendRequestsRequest(value: object): value is FriendsListIncomingFriendRequestsRequest {
    if (!('userToken' in value) || value['userToken'] === undefined) return false;
    return true;
}

export function FriendsListIncomingFriendRequestsRequestFromJSON(json: any): FriendsListIncomingFriendRequestsRequest {
    return FriendsListIncomingFriendRequestsRequestFromJSONTyped(json, false);
}

export function FriendsListIncomingFriendRequestsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FriendsListIncomingFriendRequestsRequest {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'userToken': json['userToken'],
    };
}

export function FriendsListIncomingFriendRequestsRequestToJSON(value?: FriendsListIncomingFriendRequestsRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'userToken': value['userToken'],
    };
}

