// This file is auto-generated by the Rivet (https://rivet.gg) build system.
//
// Do not edit this file directly.

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface RateLimitThrottlePublicRequest
 */
export interface RateLimitThrottlePublicRequest {}

/**
 * Check if a given object implements the RateLimitThrottlePublicRequest interface.
 */
export function instanceOfRateLimitThrottlePublicRequest(
  _value: object,
): _value is RateLimitThrottlePublicRequest {
  return true;
}

export function RateLimitThrottlePublicRequestFromJSON(
  json: any,
): RateLimitThrottlePublicRequest {
  return RateLimitThrottlePublicRequestFromJSONTyped(json, false);
}

export function RateLimitThrottlePublicRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RateLimitThrottlePublicRequest {
  if (json == null) {
    return json;
  }
  return {};
}

export function RateLimitThrottlePublicRequestToJSON(
  value?: RateLimitThrottlePublicRequest | null,
): any {
  if (value == null) {
    return value;
  }
  return {};
}
