// This file is auto-generated by the Rivet (https://rivet.gg) build system.
//
// Do not edit this file directly.

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface RivetCallRequest
 */
export interface RivetCallRequest {}

/**
 * Check if a given object implements the RivetCallRequest interface.
 */
export function instanceOfRivetCallRequest(
  _value: object,
): _value is RivetCallRequest {
  return true;
}

export function RivetCallRequestFromJSON(json: any): RivetCallRequest {
  return RivetCallRequestFromJSONTyped(json, false);
}

export function RivetCallRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RivetCallRequest {
  if (json == null) {
    return json;
  }
  return {};
}

export function RivetCallRequestToJSON(value?: RivetCallRequest | null): any {
  if (value == null) {
    return value;
  }
  return {};
}
