// This file is auto-generated by the Rivet (https://rivet.gg) build system.
//
// Do not edit this file directly.

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface TokensCreateRequest
 */
export interface TokensCreateRequest {}

/**
 * Check if a given object implements the TokensCreateRequest interface.
 */
export function instanceOfTokensCreateRequest(
  _value: object,
): _value is TokensCreateRequest {
  return true;
}

export function TokensCreateRequestFromJSON(json: any): TokensCreateRequest {
  return TokensCreateRequestFromJSONTyped(json, false);
}

export function TokensCreateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TokensCreateRequest {
  if (json == null) {
    return json;
  }
  return {};
}

export function TokensCreateRequestToJSON(
  value?: TokensCreateRequest | null,
): any {
  if (value == null) {
    return value;
  }
  return {};
}
