// This file is auto-generated by the Rivet (https://rivet.gg) build system.
//
// Do not edit this file directly.

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface TokensFetchByTokenResponse
 */
export interface TokensFetchByTokenResponse {}

/**
 * Check if a given object implements the TokensFetchByTokenResponse interface.
 */
export function instanceOfTokensFetchByTokenResponse(
  _value: object,
): _value is TokensFetchByTokenResponse {
  return true;
}

export function TokensFetchByTokenResponseFromJSON(
  json: any,
): TokensFetchByTokenResponse {
  return TokensFetchByTokenResponseFromJSONTyped(json, false);
}

export function TokensFetchByTokenResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): TokensFetchByTokenResponse {
  if (json == null) {
    return json;
  }
  return {};
}

export function TokensFetchByTokenResponseToJSON(
  value?: TokensFetchByTokenResponse | null,
): any {
  if (value == null) {
    return value;
  }
  return {};
}
