// This file is auto-generated by the Rivet (https://rivet.gg) build system.
//
// Do not edit this file directly.

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface UsersFetchByUsernameResponse
 */
export interface UsersFetchByUsernameResponse {}

/**
 * Check if a given object implements the UsersFetchByUsernameResponse interface.
 */
export function instanceOfUsersFetchByUsernameResponse(
  _value: object,
): _value is UsersFetchByUsernameResponse {
  return true;
}

export function UsersFetchByUsernameResponseFromJSON(
  json: any,
): UsersFetchByUsernameResponse {
  return UsersFetchByUsernameResponseFromJSONTyped(json, false);
}

export function UsersFetchByUsernameResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UsersFetchByUsernameResponse {
  if (json == null) {
    return json;
  }
  return {};
}

export function UsersFetchByUsernameResponseToJSON(
  value?: UsersFetchByUsernameResponse | null,
): any {
  if (value == null) {
    return value;
  }
  return {};
}
