// This file is auto-generated by the Rivet (https://rivet.gg) build system.
//
// Do not edit this file directly.

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface UsersCreateRequest
 */
export interface UsersCreateRequest {}

/**
 * Check if a given object implements the UsersCreateRequest interface.
 */
export function instanceOfUsersCreateRequest(
  _value: object,
): _value is UsersCreateRequest {
  return true;
}

export function UsersCreateRequestFromJSON(json: any): UsersCreateRequest {
  return UsersCreateRequestFromJSONTyped(json, false);
}

export function UsersCreateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UsersCreateRequest {
  if (json == null) {
    return json;
  }
  return {};
}

export function UsersCreateRequestToJSON(
  value?: UsersCreateRequest | null,
): any {
  if (value == null) {
    return value;
  }
  return {};
}
