// This file is auto-generated by the Rivet (https://rivet.gg) build system.
//
// Do not edit this file directly.

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface UsersFetchByUsernameRequest
 */
export interface UsersFetchByUsernameRequest {}

/**
 * Check if a given object implements the UsersFetchByUsernameRequest interface.
 */
export function instanceOfUsersFetchByUsernameRequest(
  _value: object,
): _value is UsersFetchByUsernameRequest {
  return true;
}

export function UsersFetchByUsernameRequestFromJSON(
  json: any,
): UsersFetchByUsernameRequest {
  return UsersFetchByUsernameRequestFromJSONTyped(json, false);
}

export function UsersFetchByUsernameRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UsersFetchByUsernameRequest {
  if (json == null) {
    return json;
  }
  return {};
}

export function UsersFetchByUsernameRequestToJSON(
  value?: UsersFetchByUsernameRequest | null,
): any {
  if (value == null) {
    return value;
  }
  return {};
}
