// This file is auto-generated by the Open Game Backend (https://opengb.dev) build system.
//
// Do not edit this file directly.
//
// Generated at 2024-09-12T00:20:05.868Z

/* tslint:disable */
/* eslint-disable */

/**
 * @export
 * @interface UsersCreateResponse
 */
export interface UsersCreateResponse {}

/**
 * Check if a given object implements the UsersCreateResponse interface.
 */
export function instanceOfUsersCreateResponse(
  _value: object,
): _value is UsersCreateResponse {
  return true;
}

export function UsersCreateResponseFromJSON(json: any): UsersCreateResponse {
  return UsersCreateResponseFromJSONTyped(json, false);
}

export function UsersCreateResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UsersCreateResponse {
  if (json == null) {
    return json;
  }
  return {};
}

export function UsersCreateResponseToJSON(
  value?: UsersCreateResponse | null,
): any {
  if (value == null) {
    return value;
  }
  return {};
}
