#!/usr/bin/env pwsh

$ErrorActionPreference = 'Stop'

[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

# Create bin directory for Rivet
$BinDir = $env:BIN_DIR
$RivetInstall = if ($BinDir) {
	$BinDir
} else {
	"${Home}\.rivet\bin"
}

if (!(Test-Path $RivetInstall)) {
	New-Item $RivetInstall -ItemType Directory | Out-Null
}

$RivetZip = "$RivetInstall\rivet.zip"  # Path where the ZIP is downloaded
$RivetExeCi = "$RivetInstall\rivet-cli.exe"  # Default name generated by CI
$RivetExe = "$RivetInstall\rivet.exe"  # Name we will move binary to
$AssetName = 'rivet-cli-x86_64-pc-windows-msvc'
$FileName = "${AssetName}.zip"

# Auto-select version to install
#
# We have to find last version with an asset so we don't break the installer
# when the assets for a new version are still generating
$Version = $env:RIVET_CLI_VERSION
if (!$Version) {
	$Releases = Invoke-RestMethod -Uri "https://api.github.com/repos/rivet-gg/cli/releases"

	foreach ($Release in $Releases) {
		if (-not $Release.prerelease) {
			$SelectedAssets = $Release.assets | Select-Object -ExpandProperty name | Where-Object { $_ -eq $FileName }
			if ($SelectedAssets) {
				$Version = $Release.tag_name
				Break
			}
		}
	}

	if (!$Version) {
		throw 'Failed to determine version to install'
	}
}

Write-Host
Write-Host "> Installing Rivet CLI ${Version}"

# Download CLI
$DownloadUrl = "https://github.com/rivet-gg/cli/releases/download/${Version}/${FileName}"
Write-Host
Write-Host "> Downloading ${DownloadUrl}"
Invoke-WebRequest $DownloadUrl -OutFile $RivetZip -UseBasicParsing

# Extract archive
Write-Host
Write-Host "> Extracting rivet.zip"
Remove-Item $RivetExe -ErrorAction SilentlyContinue
Remove-Item $RivetExeCi -ErrorAction SilentlyContinue
if (Get-Command Expand-Archive -ErrorAction SilentlyContinue) {
	Expand-Archive $RivetZip -Destination $RivetInstall -Force
} else {
	Add-Type -AssemblyName System.IO.Compression.FileSystem
	[IO.Compression.ZipFile]::ExtractToDirectory($RivetZip, $RivetInstall)
}
Remove-Item $RivetZip

# Rename from rivet-cli to rivet, since rivet-cli is the default name generated by CI
Rename-Item -Path $RivetExeCi -NewName $RivetExe

# Install CLI
Write-Host
Write-Host "> Installing rivet"
$User = [System.EnvironmentVariableTarget]::User
$Path = [System.Environment]::GetEnvironmentVariable('Path', $User)
if (!(";${Path};".ToLower() -like "*;${RivetInstall};*".ToLower())) {
	[System.Environment]::SetEnvironmentVariable('Path', "${Path};${RivetInstall}", $User)
	$Env:Path += ";${RivetInstall}"
}

Write-Host
Write-Host "> Checking installation"
rivet.exe --version

Write-Host
Write-Host "Rivet was installed successfully to ${RivetExe}."
Write-Host "Run 'rivet --help' to get started."
Write-Host
