[package]
name = "rivet-cli"
version = "2.0.0-rc.4"
edition = "2021"
license = "Apache-2.0"
rust-version = "1.75"
repository = "https://github.com/rivet-gg/cli"

[[bin]]
name = "rivet"
path = "src/main.rs"

[features]
default = ["sentry"]
sentry = []

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
toolchain = { version = "0.1.0", path = "../toolchain", package = "rivet-toolchain" }
tokio = { version = "1.40.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.120"
anyhow = "1.0"
uuid = { version = "1.11.0", features = ["v4"] }
url = { version = "2.5.3", features = ["serde"] }
base64 = "0.22.1"
kv-str = { version = "0.1.0", path = "../kv-str" }
inquire = "0.7.5"
webbrowser = "1.0.2"
sentry = { version = "0.34.0", features = ["anyhow"] }
sysinfo = "0.32.0"
ctrlc = "3.4.5"

[dependencies.async-posthog]
git = "https://github.com/rivet-gg/posthog-rs"
rev = "ef4e80e"

[build-dependencies]
anyhow = "1.0"

[build-dependencies.vergen-git2]
version = "1.0.0"
features = [
  "build",
  "cargo",
  "rustc"
]

