/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct GamesGameIdNamespacesNamespaceIdTokensDevelopmentLobbyPorts {
    #[serde(rename = "source")]
    pub source: i32,
    #[serde(rename = "target")]
    pub target: i32,
    #[serde(rename = "hostname")]
    pub hostname: String,
}

impl GamesGameIdNamespacesNamespaceIdTokensDevelopmentLobbyPorts {
    pub fn new(
        source: i32,
        target: i32,
        hostname: String,
    ) -> GamesGameIdNamespacesNamespaceIdTokensDevelopmentLobbyPorts {
        GamesGameIdNamespacesNamespaceIdTokensDevelopmentLobbyPorts {
            source,
            target,
            hostname,
        }
    }
}
