/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BillingTransfer {
	#[serde(rename = "amount")]
	pub amount: i64,
	#[serde(rename = "description", skip_serializing_if = "Option::is_none")]
	pub description: Option<String>,
	#[serde(rename = "created_ts")]
	pub created_ts: i64,
	#[serde(rename = "status")]
	pub status: crate::models::BillingStatus,
}

impl BillingTransfer {
	pub fn new(
		amount: i64,
		created_ts: i64,
		status: crate::models::BillingStatus,
	) -> BillingTransfer {
		BillingTransfer {
			amount,
			description: None,
			created_ts,
			status,
		}
	}
}
