/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject3 {
    #[serde(rename = "version_id")]
    pub version_id: String,
}

impl InlineObject3 {
    pub fn new(version_id: String) -> InlineObject3 {
        InlineObject3 { version_id }
    }
}
