/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject4 {
    #[serde(rename = "lobby_ports")]
    pub lobby_ports: Vec<crate::models::GamesGameIdNamespacesNamespaceIdTokensDevelopmentLobbyPorts>,
}

impl InlineObject4 {
    pub fn new(lobby_ports: Vec<crate::models::GamesGameIdNamespacesNamespaceIdTokensDevelopmentLobbyPorts>) -> InlineObject4 {
        InlineObject4 {
            lobby_ports,
        }
    }
}


