/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject6 {
    #[serde(rename = "lobby_count_max")]
    pub lobby_count_max: i32,
    #[serde(rename = "max_players")]
    pub max_players: i32,
}

impl InlineObject6 {
    pub fn new(lobby_count_max: i32, max_players: i32) -> InlineObject6 {
        InlineObject6 {
            lobby_count_max,
            max_players,
        }
    }
}


