/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse20013 {
	#[serde(rename = "builds")]
	pub builds: Vec<crate::models::BuildSummary>,
}

impl InlineResponse20013 {
	pub fn new(builds: Vec<crate::models::BuildSummary>) -> InlineResponse20013 {
		InlineResponse20013 { builds }
	}
}
