/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20021 {
    #[serde(rename = "perf_lists")]
    pub perf_lists: Vec<crate::models::SvcPerf>,
}

impl InlineResponse20021 {
    pub fn new(perf_lists: Vec<crate::models::SvcPerf>) -> InlineResponse20021 {
        InlineResponse20021 {
            perf_lists,
        }
    }
}


