/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse20017 {
    #[serde(rename = "payments")]
    pub payments: Vec<crate::models::BillingPayment>,
    #[serde(rename = "end_payment_id")]
    pub end_payment_id: String,
}

impl InlineResponse20017 {
    pub fn new(payments: Vec<crate::models::BillingPayment>, end_payment_id: String) -> InlineResponse20017 {
        InlineResponse20017 {
            payments,
            end_payment_id,
        }
    }
}
