/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse20019 {
	#[serde(rename = "url")]
	pub url: String,
}

impl InlineResponse20019 {
	pub fn new(url: String) -> InlineResponse20019 {
		InlineResponse20019 { url }
	}
}
