/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse2005 {
    #[serde(rename = "namespace_id")]
    pub namespace_id: String,
}

impl InlineResponse2005 {
    pub fn new(namespace_id: String) -> InlineResponse2005 {
        InlineResponse2005 { namespace_id }
    }
}
