/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse200AgentIdentity {
	#[serde(rename = "identity_id")]
	pub identity_id: String,
}

impl InlineResponse200AgentIdentity {
	pub fn new(identity_id: String) -> InlineResponse200AgentIdentity {
		InlineResponse200AgentIdentity { identity_id }
	}
}
