/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse200Agent {
	#[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
	pub identity: Option<Box<crate::models::InlineResponse200AgentIdentity>>,
	#[serde(rename = "game_cloud", skip_serializing_if = "Option::is_none")]
	pub game_cloud: Option<Box<crate::models::InlineResponse200AgentGameCloud>>,
}

impl InlineResponse200Agent {
	pub fn new() -> InlineResponse200Agent {
		InlineResponse200Agent {
			identity: None,
			game_cloud: None,
		}
	}
}
