/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InlineResponse20012 {
	#[serde(rename = "site_id")]
	pub site_id: String,
	#[serde(rename = "upload_id")]
	pub upload_id: String,
	#[serde(rename = "presigned_requests")]
	pub presigned_requests: Vec<crate::models::UploadPresignedRequest>,
}

impl InlineResponse20012 {
	pub fn new(
		site_id: String,
		upload_id: String,
		presigned_requests: Vec<crate::models::UploadPresignedRequest>,
	) -> InlineResponse20012 {
		InlineResponse20012 {
			site_id,
			upload_id,
			presigned_requests,
		}
	}
}
