/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineResponse20017 {
    #[serde(rename = "errors")]
    pub errors: Vec<Vec<String>>,
}

impl InlineResponse20017 {
    pub fn new(errors: Vec<Vec<String>>) -> InlineResponse20017 {
        InlineResponse20017 {
            errors,
        }
    }
}


