/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LobbyGroupRuntimeDockerEnvVar {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl LobbyGroupRuntimeDockerEnvVar {
    pub fn new(key: String, value: String) -> LobbyGroupRuntimeDockerEnvVar {
        LobbyGroupRuntimeDockerEnvVar {
            key,
            value,
        }
    }
}


