/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LobbyGroup {
	#[serde(rename = "name_id")]
	pub name_id: String,
	#[serde(rename = "regions")]
	pub regions: Vec<crate::models::LobbyGroupRegion>,
	#[serde(rename = "max_players_normal")]
	pub max_players_normal: i32,
	#[serde(rename = "max_players_direct")]
	pub max_players_direct: i32,
	#[serde(rename = "max_players_party")]
	pub max_players_party: i32,
	#[serde(rename = "runtime")]
	pub runtime: Box<crate::models::LobbyGroupRuntime>,
}

impl LobbyGroup {
	pub fn new(
		name_id: String,
		regions: Vec<crate::models::LobbyGroupRegion>,
		max_players_normal: i32,
		max_players_direct: i32,
		max_players_party: i32,
		runtime: crate::models::LobbyGroupRuntime,
	) -> LobbyGroup {
		LobbyGroup {
			name_id,
			regions,
			max_players_normal,
			max_players_direct,
			max_players_party,
			runtime: Box::new(runtime),
		}
	}
}
