/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct LobbyGroupRegions {
    #[serde(rename = "region_id")]
    pub region_id: String,
    #[serde(rename = "tier_name_id")]
    pub tier_name_id: String,
}

impl LobbyGroupRegions {
    pub fn new(region_id: String, tier_name_id: String) -> LobbyGroupRegions {
        LobbyGroupRegions {
            region_id,
            tier_name_id,
        }
    }
}


