/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LogsPerfMark {
	#[serde(rename = "label")]
	pub label: String,
	#[serde(rename = "ts")]
	pub ts: i64,
	#[serde(rename = "ray_id", skip_serializing_if = "Option::is_none")]
	pub ray_id: Option<String>,
	#[serde(rename = "req_id", skip_serializing_if = "Option::is_none")]
	pub req_id: Option<String>,
}

impl LogsPerfMark {
	pub fn new(label: String, ts: i64) -> LogsPerfMark {
		LogsPerfMark {
			label,
			ts,
			ray_id: None,
			req_id: None,
		}
	}
}
