/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MatchmakerCaptcha {
    #[serde(rename = "hcaptcha", skip_serializing_if = "Option::is_none")]
    pub hcaptcha: Option<Box<crate::models::MatchmakerCaptchaHcaptcha>>,
    #[serde(rename = "requests_before_reverify")]
    pub requests_before_reverify: i32,
    #[serde(rename = "verification_ttl")]
    pub verification_ttl: i64,
}

impl MatchmakerCaptcha {
    pub fn new(requests_before_reverify: i32, verification_ttl: i64) -> MatchmakerCaptcha {
        MatchmakerCaptcha {
            hcaptcha: None,
            requests_before_reverify,
            verification_ttl,
        }
    }
}


