/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NamespaceFull {
	#[serde(rename = "namespace_id")]
	pub namespace_id: String,
	#[serde(rename = "create_ts")]
	pub create_ts: i64,
	#[serde(rename = "display_name")]
	pub display_name: String,
	#[serde(rename = "version_id")]
	pub version_id: String,
	#[serde(rename = "name_id")]
	pub name_id: String,
	#[serde(rename = "config")]
	pub config: Box<crate::models::CloudNamespaceConfig>,
}

impl NamespaceFull {
	pub fn new(
		namespace_id: String,
		create_ts: i64,
		display_name: String,
		version_id: String,
		name_id: String,
		config: crate::models::CloudNamespaceConfig,
	) -> NamespaceFull {
		NamespaceFull {
			namespace_id,
			create_ts,
			display_name,
			version_id,
			name_id,
			config: Box::new(config),
		}
	}
}
