/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegionTierExpenses {
    #[serde(rename = "region_id")]
    pub region_id: String,
    #[serde(rename = "tier_name_id")]
    pub tier_name_id: String,
    #[serde(rename = "expenses")]
    pub expenses: i32,
    #[serde(rename = "create_ts", skip_serializing_if = "Option::is_none")]
    pub create_ts: Option<i32>,
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
}

impl RegionTierExpenses {
    pub fn new(region_id: String, tier_name_id: String, expenses: i32) -> RegionTierExpenses {
        RegionTierExpenses {
            region_id,
            tier_name_id,
            expenses,
            create_ts: None,
            display_name: None,
        }
    }
}


