/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RegionSummary {
	#[serde(rename = "region_id")]
	pub region_id: String,
	#[serde(rename = "provider")]
	pub provider: String,
	#[serde(rename = "universal_region")]
	pub universal_region: i32,
	#[serde(rename = "provider_display_name")]
	pub provider_display_name: String,
	#[serde(rename = "region_display_name")]
	pub region_display_name: String,
}

impl RegionSummary {
	pub fn new(
		region_id: String,
		provider: String,
		universal_region: i32,
		provider_display_name: String,
		region_display_name: String,
	) -> RegionSummary {
		RegionSummary {
			region_id,
			provider,
			universal_region,
			provider_display_name,
			region_display_name,
		}
	}
}
