/*
 * Rivet Cloud
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SvcMetrics {
	#[serde(rename = "job")]
	pub job: String,
	#[serde(rename = "cpu")]
	pub cpu: Vec<f32>,
	#[serde(rename = "memory")]
	pub memory: Vec<i64>,
	#[serde(rename = "memory_max")]
	pub memory_max: Vec<i64>,
	#[serde(rename = "allocated_memory")]
	pub allocated_memory: i64,
}

impl SvcMetrics {
	pub fn new(
		job: String,
		cpu: Vec<f32>,
		memory: Vec<i64>,
		memory_max: Vec<i64>,
		allocated_memory: i64,
	) -> SvcMetrics {
		SvcMetrics {
			job,
			cpu,
			memory,
			memory_max,
			allocated_memory,
		}
	}
}
