/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ChatGetDirectThreadOutput {
    #[serde(rename = "identity", skip_serializing_if = "Option::is_none")]
    pub identity: Option<Box<crate::models::IdentityHandle>>,
    /// A universally unique identifier.
    #[serde(rename = "thread_id", skip_serializing_if = "Option::is_none")]
    pub thread_id: Option<String>,
}

impl ChatGetDirectThreadOutput {
    pub fn new() -> ChatGetDirectThreadOutput {
        ChatGetDirectThreadOutput {
            identity: None,
            thread_id: None,
        }
    }
}


