/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudGamesNamespacesUpdateGameNamespaceVersionInput {
    /// A universally unique identifier.
    #[serde(rename = "version_id")]
    pub version_id: String,
}

impl CloudGamesNamespacesUpdateGameNamespaceVersionInput {
    pub fn new(version_id: String) -> CloudGamesNamespacesUpdateGameNamespaceVersionInput {
        CloudGamesNamespacesUpdateGameNamespaceVersionInput {
            version_id,
        }
    }
}


