/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudGamesCreateGameVersionInput {
    /// Represent a resource's readable display name.
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "config")]
    pub config: Box<crate::models::CommonsCloudVersionConfig>,
}

impl CloudGamesCreateGameVersionInput {
    pub fn new(display_name: String, config: crate::models::CommonsCloudVersionConfig) -> CloudGamesCreateGameVersionInput {
        CloudGamesCreateGameVersionInput {
            display_name,
            config: Box::new(config),
        }
    }
}


