/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CloudGetRegionTiersOutput {
    /// A list of region server tiers.
    #[serde(rename = "tiers")]
    pub tiers: Vec<crate::models::CloudRegionTier>,
}

impl CloudGetRegionTiersOutput {
    pub fn new(tiers: Vec<crate::models::CloudRegionTier>) -> CloudGetRegionTiersOutput {
        CloudGetRegionTiersOutput {
            tiers,
        }
    }
}


