/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CloudVersionIdentityConfig : Identity configuration for a given version.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudVersionIdentityConfig {
    #[serde(rename = "custom_avatars")]
    pub custom_avatars: Vec<crate::models::CloudVersionIdentityCustomAvatar>,
    #[serde(rename = "custom_display_names")]
    pub custom_display_names: Vec<crate::models::CloudVersionIdentityCustomDisplayName>,
}

impl CloudVersionIdentityConfig {
    /// Identity configuration for a given version.
    pub fn new(custom_avatars: Vec<crate::models::CloudVersionIdentityCustomAvatar>, custom_display_names: Vec<crate::models::CloudVersionIdentityCustomDisplayName>) -> CloudVersionIdentityConfig {
        CloudVersionIdentityConfig {
            custom_avatars,
            custom_display_names,
        }
    }
}


