/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CloudAvgPlayDurationByGameModeDataSet {
	#[serde(rename = "duration")]
	pub duration: Vec<i64>,
	#[serde(rename = "game_mode_name_id")]
	pub game_mode_name_id: Vec<String>,
}

impl CloudAvgPlayDurationByGameModeDataSet {
	pub fn new(
		duration: Vec<i64>,
		game_mode_name_id: Vec<String>,
	) -> CloudAvgPlayDurationByGameModeDataSet {
		CloudAvgPlayDurationByGameModeDataSet {
			duration,
			game_mode_name_id,
		}
	}
}
