/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CloudDestroyedLobbiesByFailureDataSet {
	#[serde(rename = "destroyed_lobby_count")]
	pub destroyed_lobby_count: Vec<i64>,
	#[serde(rename = "failed")]
	pub failed: Vec<bool>,
	#[serde(rename = "ts")]
	pub ts: Vec<i64>,
}

impl CloudDestroyedLobbiesByFailureDataSet {
	pub fn new(
		destroyed_lobby_count: Vec<i64>,
		failed: Vec<bool>,
		ts: Vec<i64>,
	) -> CloudDestroyedLobbiesByFailureDataSet {
		CloudDestroyedLobbiesByFailureDataSet {
			destroyed_lobby_count,
			failed,
			ts,
		}
	}
}
