/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudCdnVersionMiddleware {
    #[serde(rename = "kind")]
    pub kind: Box<crate::models::CloudCdnVersionMiddlewareKind>,
}

impl CloudCdnVersionMiddleware {
    pub fn new(kind: crate::models::CloudCdnVersionMiddlewareKind) -> CloudCdnVersionMiddleware {
        CloudCdnVersionMiddleware {
            kind: Box::new(kind),
        }
    }
}


