/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CloudGamesNamespacesInspectOutput {
    #[serde(rename = "agent")]
    pub agent: Box<crate::models::CloudAuthAgent>,
}

impl CloudGamesNamespacesInspectOutput {
    pub fn new(agent: crate::models::CloudAuthAgent) -> CloudGamesNamespacesInspectOutput {
        CloudGamesNamespacesInspectOutput {
            agent: Box::new(agent),
        }
    }
}


