/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CloudLobbyCountByRegionDataSet {
	#[serde(rename = "lobby_count")]
	pub lobby_count: Vec<i64>,
	#[serde(rename = "region_name_id")]
	pub region_name_id: Vec<String>,
	#[serde(rename = "ts")]
	pub ts: Vec<i64>,
}

impl CloudLobbyCountByRegionDataSet {
	pub fn new(
		lobby_count: Vec<i64>,
		region_name_id: Vec<String>,
		ts: Vec<i64>,
	) -> CloudLobbyCountByRegionDataSet {
		CloudLobbyCountByRegionDataSet {
			lobby_count,
			region_name_id,
			ts,
		}
	}
}
