/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CloudGamesGetAnalyticsResponse {
	#[serde(rename = "data_sets")]
	pub data_sets: Vec<crate::models::CloudNamespaceAnalyticsDataSet>,
}

impl CloudGamesGetAnalyticsResponse {
	pub fn new(
		data_sets: Vec<crate::models::CloudNamespaceAnalyticsDataSet>,
	) -> CloudGamesGetAnalyticsResponse {
		CloudGamesGetAnalyticsResponse { data_sets }
	}
}
