/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CloudGamesLogStream {
    #[serde(rename = "std_out")]
    Out,
    #[serde(rename = "std_err")]
    Err,

}

impl ToString for CloudGamesLogStream {
    fn to_string(&self) -> String {
        match self {
            Self::Out => String::from("std_out"),
            Self::Err => String::from("std_err"),
        }
    }
}

impl Default for CloudGamesLogStream {
    fn default() -> CloudGamesLogStream {
        Self::Out
    }
}




