/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CloudGroupBillingCheckoutResponse {
	/// The URL of the checkout session.
	#[serde(rename = "url")]
	pub url: String,
}

impl CloudGroupBillingCheckoutResponse {
	pub fn new(url: String) -> CloudGroupBillingCheckoutResponse {
		CloudGroupBillingCheckoutResponse { url }
	}
}
