/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CloudLobbyReadyTimeDataSet {
	#[serde(rename = "ready_duration")]
	pub ready_duration: Vec<i64>,
	#[serde(rename = "ts")]
	pub ts: Vec<i64>,
}

impl CloudLobbyReadyTimeDataSet {
	pub fn new(ready_duration: Vec<i64>, ts: Vec<i64>) -> CloudLobbyReadyTimeDataSet {
		CloudLobbyReadyTimeDataSet { ready_duration, ts }
	}
}
