/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CloudGamesGetLobbyLogsOutput {
    /// Sorted old to new.
    #[serde(rename = "lines")]
    pub lines: Vec<String>,
    /// Sorted old to new.
    #[serde(rename = "timestamps")]
    pub timestamps: Vec<String>,
    #[serde(rename = "watch")]
    pub watch: Box<crate::models::WatchResponse>,
}

impl CloudGamesGetLobbyLogsOutput {
    pub fn new(lines: Vec<String>, timestamps: Vec<String>, watch: crate::models::WatchResponse) -> CloudGamesGetLobbyLogsOutput {
        CloudGamesGetLobbyLogsOutput {
            lines,
            timestamps,
            watch: Box::new(watch),
        }
    }
}


