/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CloudIdentityVersionConfig : Identity configuration for a given version.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CloudIdentityVersionConfig {
    #[serde(rename = "custom_display_names")]
    pub custom_display_names: Vec<crate::models::CloudCustomDisplayName>,
    #[serde(rename = "custom_avatars")]
    pub custom_avatars: Vec<crate::models::CloudCustomAvatar>,
}

impl CloudIdentityVersionConfig {
    /// Identity configuration for a given version.
    pub fn new(custom_display_names: Vec<crate::models::CloudCustomDisplayName>, custom_avatars: Vec<crate::models::CloudCustomAvatar>) -> CloudIdentityVersionConfig {
        CloudIdentityVersionConfig {
            custom_display_names,
            custom_avatars,
        }
    }
}


