/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CloudAvgPlayDurationByRegionDataSet {
	#[serde(rename = "duration")]
	pub duration: Vec<i64>,
	#[serde(rename = "region_name_id")]
	pub region_name_id: Vec<String>,
}

impl CloudAvgPlayDurationByRegionDataSet {
	pub fn new(
		duration: Vec<i64>,
		region_name_id: Vec<String>,
	) -> CloudAvgPlayDurationByRegionDataSet {
		CloudAvgPlayDurationByRegionDataSet {
			duration,
			region_name_id,
		}
	}
}
