/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommonsChatTopicParty {
    #[serde(rename = "party")]
    pub party: Box<crate::models::CommonsPartyHandle>,
}

impl CommonsChatTopicParty {
    pub fn new(party: crate::models::CommonsPartyHandle) -> CommonsChatTopicParty {
        CommonsChatTopicParty {
            party: Box::new(party),
        }
    }
}


