/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CommonsRegionTier : A region server tier.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommonsRegionTier {
    /// A human readable short identifier used to references resources. Different than a `rivet.common#Uuid` because this is intended to be human readable. Different than `rivet.common#DisplayName` because this should not include special characters and be short.
    #[serde(rename = "tier_name_id")]
    pub tier_name_id: String,
    /// Together with the denominator, denotes the portion of the CPU a given server uses.
    #[serde(rename = "rivet_cores_numerator", skip_serializing_if = "Option::is_none")]
    pub rivet_cores_numerator: Option<f64>,
    /// Together with the numerator, denotes the portion of the CPU a given server uses.
    #[serde(rename = "rivet_cores_denominator", skip_serializing_if = "Option::is_none")]
    pub rivet_cores_denominator: Option<f64>,
    /// CPU frequency (MHz).
    #[serde(rename = "cpu", skip_serializing_if = "Option::is_none")]
    pub cpu: Option<f64>,
    /// Allocated memory (MB).
    #[serde(rename = "memory", skip_serializing_if = "Option::is_none")]
    pub memory: Option<f64>,
    /// Allocated disk space (MB).
    #[serde(rename = "disk", skip_serializing_if = "Option::is_none")]
    pub disk: Option<f64>,
    /// Internet bandwidth (MB).
    #[serde(rename = "bandwidth", skip_serializing_if = "Option::is_none")]
    pub bandwidth: Option<f64>,
    /// Price billed for every second this server is running (in quadrillionth USD, 1,000,000,000,000 = $1.00).
    #[serde(rename = "price_per_second", skip_serializing_if = "Option::is_none")]
    pub price_per_second: Option<f64>,
}

impl CommonsRegionTier {
    /// A region server tier.
    pub fn new(tier_name_id: String) -> CommonsRegionTier {
        CommonsRegionTier {
            tier_name_id,
            rivet_cores_numerator: None,
            rivet_cores_denominator: None,
            cpu: None,
            memory: None,
            disk: None,
            bandwidth: None,
            price_per_second: None,
        }
    }
}


