/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CommonsPartyMemberStateMatchmakerLobby : A party member state denoting that the member is in a lobby.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommonsPartyMemberStateMatchmakerLobby {
    #[serde(rename = "player_id")]
    pub player_id: uuid::Uuid,
}

impl CommonsPartyMemberStateMatchmakerLobby {
    /// A party member state denoting that the member is in a lobby.
    pub fn new(player_id: uuid::Uuid) -> CommonsPartyMemberStateMatchmakerLobby {
        CommonsPartyMemberStateMatchmakerLobby {
            player_id,
        }
    }
}


