/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CommonsAuthAgentIdentity : The current authenticated identity.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommonsAuthAgentIdentity {
    #[serde(rename = "identity_id")]
    pub identity_id: uuid::Uuid,
}

impl CommonsAuthAgentIdentity {
    /// The current authenticated identity.
    pub fn new(identity_id: uuid::Uuid) -> CommonsAuthAgentIdentity {
        CommonsAuthAgentIdentity {
            identity_id,
        }
    }
}


