/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CommonsLobbyGroupRuntimeDockerEnvVar : A docker environment variable.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommonsLobbyGroupRuntimeDockerEnvVar {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl CommonsLobbyGroupRuntimeDockerEnvVar {
    /// A docker environment variable.
    pub fn new(key: String, value: String) -> CommonsLobbyGroupRuntimeDockerEnvVar {
        CommonsLobbyGroupRuntimeDockerEnvVar {
            key,
            value,
        }
    }
}


