/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CommonsChatThread : A chat thread



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommonsChatThread {
    #[serde(rename = "thread_id")]
    pub thread_id: uuid::Uuid,
    /// RFC3339 timestamp
    #[serde(rename = "create_ts")]
    pub create_ts: String,
    #[serde(rename = "topic")]
    pub topic: Box<crate::models::CommonsChatTopic>,
    #[serde(rename = "tail_message", skip_serializing_if = "Option::is_none")]
    pub tail_message: Option<Box<crate::models::CommonsChatMessage>>,
    /// RFC3339 timestamp
    #[serde(rename = "last_read_ts")]
    pub last_read_ts: String,
    #[serde(rename = "unread_count")]
    pub unread_count: i32,
    #[serde(rename = "external")]
    pub external: Box<crate::models::CommonsChatThreadExternalLinks>,
}

impl CommonsChatThread {
    /// A chat thread
    pub fn new(thread_id: uuid::Uuid, create_ts: String, topic: crate::models::CommonsChatTopic, last_read_ts: String, unread_count: i32, external: crate::models::CommonsChatThreadExternalLinks) -> CommonsChatThread {
        CommonsChatThread {
            thread_id,
            create_ts,
            topic: Box::new(topic),
            tail_message: None,
            last_read_ts,
            unread_count,
            external: Box::new(external),
        }
    }
}


