/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CommonsPartyActivity : A union representing the activity of a given party.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommonsPartyActivity {
    #[serde(rename = "idle", skip_serializing_if = "Option::is_none")]
    pub idle: Option<serde_json::Value>,
    #[serde(rename = "matchmaker_finding_lobby", skip_serializing_if = "Option::is_none")]
    pub matchmaker_finding_lobby: Option<Box<crate::models::CommonsPartyActivityMatchmakerFindingLobby>>,
    #[serde(rename = "matchmaker_lobby", skip_serializing_if = "Option::is_none")]
    pub matchmaker_lobby: Option<Box<crate::models::CommonsPartyActivityMatchmakerLobby>>,
}

impl CommonsPartyActivity {
    /// A union representing the activity of a given party.
    pub fn new() -> CommonsPartyActivity {
        CommonsPartyActivity {
            idle: None,
            matchmaker_finding_lobby: None,
            matchmaker_lobby: None,
        }
    }
}


