/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CommonsIdentityVersionConfig : Identity configuration for a given version.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommonsIdentityVersionConfig {
    #[serde(rename = "custom_display_names")]
    pub custom_display_names: Vec<crate::models::CommonsCustomDisplayName>,
    #[serde(rename = "custom_avatars")]
    pub custom_avatars: Vec<crate::models::CommonsCustomAvatar>,
}

impl CommonsIdentityVersionConfig {
    /// Identity configuration for a given version.
    pub fn new(custom_display_names: Vec<crate::models::CommonsCustomDisplayName>, custom_avatars: Vec<crate::models::CommonsCustomAvatar>) -> CommonsIdentityVersionConfig {
        CommonsIdentityVersionConfig {
            custom_display_names,
            custom_avatars,
        }
    }
}


