/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CommonsPartyInvite : A party invite.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommonsPartyInvite {
    /// A universally unique identifier.
    #[serde(rename = "invite_id")]
    pub invite_id: String,
    /// RFC3339 timestamp.
    #[serde(rename = "create_ts")]
    pub create_ts: String,
    /// A JSON Web Token. Slightly modified to include a description prefix and use Protobufs of JSON.
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "alias", skip_serializing_if = "Option::is_none")]
    pub alias: Option<Box<crate::models::CommonsPartyInviteAlias>>,
    #[serde(rename = "external")]
    pub external: Box<crate::models::CommonsPartyInviteExternalLinks>,
}

impl CommonsPartyInvite {
    /// A party invite.
    pub fn new(invite_id: String, create_ts: String, token: String, external: crate::models::CommonsPartyInviteExternalLinks) -> CommonsPartyInvite {
        CommonsPartyInvite {
            invite_id,
            create_ts,
            token,
            alias: None,
            external: Box::new(external),
        }
    }
}


