/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CommonsPortRange : Range of ports that can be connected to.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommonsPortRange {
    /// Unsigned 32 bit integer.
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<f64>,
    /// Unsigned 32 bit integer.
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<f64>,
}

impl CommonsPortRange {
    /// Range of ports that can be connected to.
    pub fn new() -> CommonsPortRange {
        CommonsPortRange {
            min: None,
            max: None,
        }
    }
}


