/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CommonsCaptchaConfigHcaptcha : Captcha configuration.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommonsCaptchaConfigHcaptcha {
    #[serde(rename = "client_response")]
    pub client_response: String,
}

impl CommonsCaptchaConfigHcaptcha {
    /// Captcha configuration.
    pub fn new(client_response: String) -> CommonsCaptchaConfigHcaptcha {
        CommonsCaptchaConfigHcaptcha {
            client_response,
        }
    }
}


