/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommonsGameHandle {
    #[serde(rename = "game_id")]
    pub game_id: uuid::Uuid,
    /// A human readable short identifier used to references resources. Different than a `uuid` because this is intended to be human readable. Different than `DisplayName` because this should not include special characters and be short.
    #[serde(rename = "name_id")]
    pub name_id: String,
    #[serde(rename = "display_name")]
    pub display_name: String,
    #[serde(rename = "logo_url")]
    pub logo_url: String,
    #[serde(rename = "banner_url")]
    pub banner_url: String,
}

impl CommonsGameHandle {
    pub fn new(game_id: uuid::Uuid, name_id: String, display_name: String, logo_url: String, banner_url: String) -> CommonsGameHandle {
        CommonsGameHandle {
            game_id,
            name_id,
            display_name,
            logo_url,
            banner_url,
        }
    }
}


