/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CommonsChatSimpleTopic : Represents a topic of the given chat thread without the associated handles for the topic. 



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CommonsChatSimpleTopic {
    #[serde(rename = "group", skip_serializing_if = "Option::is_none")]
    pub group: Option<Box<crate::models::CommonsChatSimpleTopicGroup>>,
    #[serde(rename = "party", skip_serializing_if = "Option::is_none")]
    pub party: Option<Box<crate::models::CommonsChatSimpleTopicParty>>,
    #[serde(rename = "direct", skip_serializing_if = "Option::is_none")]
    pub direct: Option<Box<crate::models::CommonsChatSimpleTopicDirect>>,
}

impl CommonsChatSimpleTopic {
    /// Represents a topic of the given chat thread without the associated handles for the topic. 
    pub fn new() -> CommonsChatSimpleTopic {
        CommonsChatSimpleTopic {
            group: None,
            party: None,
            direct: None,
        }
    }
}


