/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GroupPrepareGroupAvatarUploadOutput {
    /// A universally unique identifier.
    #[serde(rename = "upload_id")]
    pub upload_id: String,
    #[serde(rename = "presigned_request")]
    pub presigned_request: Box<crate::models::CommonsUploadPresignedRequest>,
}

impl GroupPrepareGroupAvatarUploadOutput {
    pub fn new(upload_id: String, presigned_request: crate::models::CommonsUploadPresignedRequest) -> GroupPrepareGroupAvatarUploadOutput {
        GroupPrepareGroupAvatarUploadOutput {
            upload_id,
            presigned_request: Box::new(presigned_request),
        }
    }
}


