/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct GroupGetProfileOutput {
    #[serde(rename = "group")]
    pub group: Box<crate::models::GroupProfile>,
    #[serde(rename = "watch")]
    pub watch: Box<crate::models::WatchResponse>,
}

impl GroupGetProfileOutput {
    pub fn new(group: crate::models::GroupProfile, watch: crate::models::WatchResponse) -> GroupGetProfileOutput {
        GroupGetProfileOutput {
            group: Box::new(group),
            watch: Box::new(watch),
        }
    }
}


