/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GroupConsumeGroupInviteOutput {
    /// A universally unique identifier.
    #[serde(rename = "group_id", skip_serializing_if = "Option::is_none")]
    pub group_id: Option<String>,
}

impl GroupConsumeGroupInviteOutput {
    pub fn new() -> GroupConsumeGroupInviteOutput {
        GroupConsumeGroupInviteOutput {
            group_id: None,
        }
    }
}


