/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IdentityGlobalEvent : An event relevant to the current identity.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityGlobalEvent {
    /// RFC3339 timestamp
    #[serde(rename = "ts")]
    pub ts: String,
    #[serde(rename = "kind")]
    pub kind: Box<crate::models::IdentityGlobalEventKind>,
    #[serde(rename = "notification")]
    pub notification: Box<crate::models::IdentityGlobalEventNotification>,
}

impl IdentityGlobalEvent {
    /// An event relevant to the current identity.
    pub fn new(ts: String, kind: crate::models::IdentityGlobalEventKind, notification: crate::models::IdentityGlobalEventNotification) -> IdentityGlobalEvent {
        IdentityGlobalEvent {
            ts,
            kind: Box::new(kind),
            notification: Box::new(notification),
        }
    }
}


