/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct IdentityGetProfileOutput {
    #[serde(rename = "identity")]
    pub identity: Box<crate::models::IdentityProfile>,
    #[serde(rename = "watch")]
    pub watch: Box<crate::models::WatchResponse>,
}

impl IdentityGetProfileOutput {
    pub fn new(identity: crate::models::IdentityProfile, watch: crate::models::WatchResponse) -> IdentityGetProfileOutput {
        IdentityGetProfileOutput {
            identity: Box::new(identity),
            watch: Box::new(watch),
        }
    }
}


