/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PlayersConnectedRequest {
    #[serde(rename = "player_token")]
    pub player_token: String,
}

impl PlayersConnectedRequest {
    pub fn new(player_token: String) -> PlayersConnectedRequest {
        PlayersConnectedRequest {
            player_token,
        }
    }
}


