/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PortalGetSuggestedGamesOutput {
    /// A list of game summaries.
    #[serde(rename = "games")]
    pub games: Vec<crate::models::CommonsGameSummary>,
    #[serde(rename = "watch")]
    pub watch: Box<crate::models::CommonsWatchResponse>,
}

impl PortalGetSuggestedGamesOutput {
    pub fn new(games: Vec<crate::models::CommonsGameSummary>, watch: crate::models::CommonsWatchResponse) -> PortalGetSuggestedGamesOutput {
        PortalGetSuggestedGamesOutput {
            games,
            watch: Box::new(watch),
        }
    }
}


