/*
 * Rivet API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SendChatMessageInput {
    #[serde(rename = "topic")]
    pub topic: Box<crate::models::ChatSendChatTopic>,
    #[serde(rename = "message_body")]
    pub message_body: Box<crate::models::ChatSendMessageBody>,
}

impl SendChatMessageInput {
    pub fn new(topic: crate::models::ChatSendChatTopic, message_body: crate::models::ChatSendMessageBody) -> SendChatMessageInput {
        SendChatMessageInput {
            topic: Box::new(topic),
            message_body: Box::new(message_body),
        }
    }
}


